version: '3.4'

services:
  businessapi:
    image: businessapi
    container_name: business_api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3030:3030
    volumes:
      - .:/usr/src/app
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: business_db
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
